---
#Author: Saed Alavinia 
#Email: saedalav@gmail.com 
#Github: github.com/saedalav 


- name: Setting uaac target
  command: "uaac target https://{{Route53Record}}/uaa --skip-ssl-validation"

- name: Obtaining API Token from Director
  command: "uaac token owner get opsman {{AdminUserName}} -p {{AdminPassword}} -s '' "

- name: Extracting UAAC access_token
  shell: "uaac context saedalav@gmail.com | grep -o -P '(?<=access_token:\ ).*(?=)'"
  register: context

- set_fact:
    UAA_ACCESS_TOKEN: "{{context.stdout}}"   


- name: Get Elastic Runtime Deployed GUID
  uri:
    url: "https://{{Route53Record}}/api/v0/deployed/products"
    return_content: yes
    method: GET
    validate_certs: no
    headers:
      Authorization: "Bearer {{UAA_ACCESS_TOKEN}}" 
      Content-Type: "application/json"
  register: staged

- set_fact: 
    ProductGUID: "{{staged.json[1].guid}}"

- debug: 
    msg: "ElasticRuntime's Product GUID is {{ProductGUID}}"



- name: Getting Admin Credentials
  uri:
    url: "https://{{Route53Record}}/api/v0/deployed/products/{{ProductGUID}}/credentials/.uaa.admin_credentials"
    return_content: yes
    method: GET
    validate_certs: no
    headers:
      Authorization: "Bearer {{UAA_ACCESS_TOKEN}}" 
      Content-Type: "application/json"
  register: admin

- set_fact: 
    AdminUser: "{{admin.json.credential.value.identity}}"
    AdminPassword: "{{admin.json.credential.value.password}}"

- debug: 
    msg: "Username:\ {{AdminUser}}    and Password:\ {{AdminPassword}}"


- name: Setting uaac target
  command: "uaac target https://uaa.{{RuntimeSystemDomain}} --skip-ssl-validation"


- name: Setting uaac target
  command: "uaac token client get {{AdminUser}} -s {{AdminPassword}}"

- name: Create a User
  command: "uaac user add {{pushUserName}} -p {{pushPassword}} --email {{pushEmail}}"

- name: Give All rights to User (Admin User)
  command: "uaac member add cloud_controller.admin {{pushUserName}}"

- name: Give All rights to User (Admin User)
  command: "uaac member add uaa.admin {{pushUserName}}"

- name: Give All rights to User (Admin User)
  command: "uaac member add scim.read {{pushUserName}}"

- name: Give All rights to User (Admin User)
  command: "uaac member add scim.write {{pushUserName}}"



