---
#Author: Saed Alavinia 
#Email: saedalav@gmail.com 
#Github: github.com/saedalav 


- name: update
  command: "sudo apt-get update"

- name: Install pip
  apt:
    name: python-pip
    update_cache: yes
    state: latest

- name: Install expect
  command: "sudo pip install pexpect"

- name: Execute
  expect:
    command: "sudo -u tempest-web RAILS_ENV=production /home/tempest-web/tempest/web/scripts/decrypt /var/tempest/workspaces/default/installation.yml /tmp/installation.yml"
    responses:
      Passphrase: "mypass"

- name: Replace 1
  command: "sed -i -e 's/blobstore_type:\ local/blobstore_type:\ s3/g' /tmp/installation.yml"

- name: Replace 2
  command: "sed -i -e 's/database_type:\ internal/database_type:\ external/g' /tmp/installation.yml"

- name: Execute
  expect:
    command: "sudo -u tempest-web RAILS_ENV=production /home/tempest-web/tempest/web/scripts/encrypt /tmp/installation.yml /var/tempest/workspaces/default/installation.yml"
    responses:
      Passphrase: "mypass"
