---
#Author: Saed Alavinia 
#Email: saedalav@gmail.com 
#Github: github.com/saedalav 


# vars file for pcf
StackName: pcf-stack
Region: us-east-1
NATKeyPair: us-east-1
OpsManInstanceType: t2.medium
AMIID: ami-e6bdd9f0
Route53Zone: alavinia.me
Route53Record: mon.alavinia.me
Route53Type: A

DecryptionPassphrase: mypass
AdminUserName: saedalav@gmail.com
AdminPassword: mypass




