---
#Launch the Cloud Formation Template located in files/sample.json & Register the output.
#- name: return motd to registered var
#  command: uaac target "https://{{Route53Record}}/uaa" --skip-ssl-validation

#- name: return var
#  command: uaac token owner get opsman "{{AdminUserName}}" -p "{{AdminPassword}}" -s ""

#- name: get context
#  command: uaac context {{AdminUserName}}
#  register: context


- name: Extracting UAAC access_token
  shell: "uaac context saedalav@gmail.com | grep -o -P '(?<=access_token:\ ).*(?=)'"
  register: context

- set_fact:
    UAA_ACCESS_TOKEN: "{{context.stdout}}"   



- name: Execute Shell Script
  shell: "curl https://{{Route53Record}}/api/v0/available_products -v -k -X POST -H 'Authorization:\ Bearer {{UAA_ACCESS_TOKEN}}' -F product[file]=@{{ElasticRuntimeFilePath}}"
#  comman: "roles/elasticruntimeupload/files/curl.sh  {{UAA_ACCESS_TOKEN}}"
  register: output

- debug: 
    msg: "{{output}}"
 

